name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12.17
      id: go
          
          
    - name: setup env
      run: |
          echo "::set-env name=GOPATH::$(go env GOPATH)"
          echo "::add-path::$(go env GOPATH)/bin"
      shell: bash

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        path: go/src/github.com/openebs/maya

    - name: Install Go Dep
      run: make bootstrap

    #- name: verify unit tests
    #  run: bash ./buildscripts/test-cov.sh
       
    - name: verify all
      run: bash ./buildscripts/travis-build.sh
      env:
        GOPATH: /home/runner/work/maya/go
